apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  ${{values.project_name_in_k8}}-ingress
  annotations:
    nginx.org/mergeable-ingress-type: "master"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    
spec:
  rules:
  - host: evolution.k8
    http:
      paths:
      - path: /${{values.project_name_in_k8}}
        pathType: Prefix
        backend:
          service:
            name:  ${{values.project_name_in_k8}}
            port:
              number: 8080