apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubeosx-ingress
  namespace: default
spec:
  rules:
    - host: kubeosx.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kubeosx-service
                port:
                  number: 8080