apiVersion: v1
kind: Secret
metadata:
  name: kubeosx-secret
  namespace: default
type: Opaque
data:
  example-key: ZXhhbXBsZS12YWx1ZQ== # base64 encoded value for 'example-value'
---
apiVersion: v1
data:
  username: YXBw
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: app-secret
type: kubernetes.io/basic-auth