apiVersion: v1
kind: Service
metadata:
  name: ${{values.project_name_in_k8}}
  labels:
    metrics-scraper: prometheus
spec:
  selector:
    app: ${{values.project_name_in_k8}}
  ports:
    - name: http
      port: 8080
      targetPort: 8080