apiVersion: v1
kind: Service
metadata:
  name: ${{values.deployment_name}}
  labels:
    metrics-scraper: prometheus
spec:
  selector:
    app: ${{values.deployment_name}}
  ports:
    - name: http
      port: 8080
      targetPort: 8080