name: GO > Build > Test > Docker

on:
  push:
    branches: [main] #dev, staging,
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test-openapi:
    uses: kubeosx/kubeos-github-workflows/.github/workflows/go-ci.yaml@main
    with:
      # need to specify working-directory as that's where the source code lives
      working-directory: .
    secrets: inherit